### ISSUE TITLE
Deb/PPA fails to install on recent Ubuntus due to obsoleted libtinyxml2-2v5

### ISSUE THREAD

**Issue by ronjouch** [RobJinman/pro_office_calc#1]
```
~ sudo dpkg -i procalc_1.0.3-0ubuntu1_amd64.deb
Selecting previously unselected package procalc.
(Reading database ... 362534 files and directories currently installed.)
Preparing to unpack procalc_1.0.3-0ubuntu1_amd64.deb ...
Unpacking procalc (1.0.3-0ubuntu1) ...
dpkg: dependency problems prevent configuration of procalc:
 procalc depends on libqt5multimedia5 (>= 5.5.1); however:
  Package libqt5multimedia5 is not installed.
 procalc depends on libtinyxml2-2v5 (>= 2.2.0); however:
   E: Package 'libtinyxml2-2v5' has no installation candidate
```

Here are [results for libtinyxml2 in the ubuntu packages](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libtinyxml2&searchon=names), `libtinyxml2-2v5` was only available for xenial (16.04LTS).

- Proper solution: a new deb that depends on `libtinyxml2-6`
- Workaround: install the xenial deb for 2v5. It worked for me without any conflicts.

**Comment by RobJinman** [comment]
Thanks, I'll try making a package for Ubuntu 18 when I get a chance.

**Comment by artlogic** [comment]
Same for Debian Stretch, which has `libtinyxml2-4`.

**Comment by RobJinman** [comment]
I've made a debian package that has tinyxml2 linked statically, which should resolve the problem. It's available from [the website](https://proofficecalculator.com).
