### ISSUE TITLE
Mention Arch Linux AUR package

### ISSUE THREAD

**Issue by ronjouch** [RobJinman/pro_office_calc#2]
I added a recipe to the Arch User Repository; Arch users can now get the game by simply installing the [`procalc-git` package](https://aur.archlinux.org/packages/procalc-git/). Feel free to mention it here in the README or the homepage 🙂.

Direct [link to the PKGBUILD recipe](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=procalc-git); I can cede ownership or co-own if you want it.

Thanks for the calculator.

**Comment by ad1217** [comment]
I also made a package, although a non-git version, named [pro_office_calc](https://aur.archlinux.org/packages/pro_office_calc/).
@ronjouch I would note that the 'chrpath' and 'patchelf' depends are not needed for Arch packaging. I am very amused that we both made packages on the same day, did you find this from BoingBoing?

**Comment by ronjouch** [comment]
@ad1217

> *"I also made a package, although a non-git version, named [pro_office_calc](https://aur.archlinux.org/packages/pro_office_calc/)"*

Cool! I'd like us to homogenize the names into `SOMETHING` & `SOMETHING-git`, then. Can be either `procalc` or `pro_office_calc`, I don't have any preference, do you?

> *"I would note that the `chrpath` and `patchelf` depends are not needed for Arch packaging"*

Thanks! Will update the pkgbuild. Your recipe also answers questions I had about depends and makedepends (this is my first package 🙂), will use yours to improve mine. Also, feedback about your package: I intentionally used the [description of the Itch.io page](https://robjinman.itch.io/pro-office-calculator), because in the context of package it felt more discoverable than the enigmatic description. Also, you should add a few keywords to your AUR package for searchability.

> *"I am very amused that we both made packages on the same day, did you find this from BoingBoing?"*

I found about it via [waxy links](https://waxy.org/2018/12/pro-office-calculator-is-a-totally-normal-calculator/) (waxy, a.k.a. Andy Baio, shares lots of cool links, he's one of the folks behind Kickstarter). Reading the boingboing page, looks like they got it via him too 🙂.

**Comment by RobJinman** [comment]
Thanks, I'll mention these in the README and possibly the website too.

I should probably also provide a standalone linux installation (tarball) via the website as that's what gets deployed if you install through Steam.
