### ISSUE TITLE
Keep mouse inside window in FPS game

### ISSUE THREAD

**Issue by gonutz** [RobJinman/pro_office_calc#6]
Moving my mouse all the way to one side of the screen will make the FPS game lose focus. This prevents me from turning around quickly.

I know that games today move the cursor to the screen center every frame, I am not sure why this does not work all the time for you.

**Comment by RobJinman** [comment]
It's probably because the window is so small. I haven't found a solution for this yet.

**Comment by gonutz** [comment]
I have tested this some more and found that focus is lost even when moving the mouse outside the window just a little bit (but very fast). Flicking the mouse left and right causes the problem.

At first I thought you were only handling the regular mouse motion events. This would have meant that you needed to grab the mouse and track its global position, as in this thread
https://stackoverflow.com/questions/1935021/getting-mousemoveevents-in-qt

But looking around it now seems to me that you have a frame timer that runs continuously and every frame you call `QCursor::setPos` to move the mouse back to the center of your window. This should actually keep working even when the mouse is outside the window.

I have not looked at the code for too long and I found instances of `setFocus()` and `setMouseTracking()` as well so which of the above do you do, react to mouse events and/or have a timer to reset the mouse to the center?

**Comment by RobJinman** [comment]
Every tick of the game loop I look at how far the mouse has drifted from centre and move the camera accordingly, then set the mouse position back to the centre.

I listen to mouse move events so I can keep m_cursor up-to-date with the latest mouse position.

**Comment by gonutz** [comment]
So this should actually work then...

I have no Qt installed at the moment, I might come back to this in a couple of days and try to figure it out. Thanks for the help so far, very cool game (I am currently stuck at the file browser, but will get it to work eventually)! :-)

**Comment by gonutz** [comment]
Yes, this does fix the problem - thank you very much!

I am a bit disappointed that I just missed my chance to fix it myself, a day of setting up my build environment and now you just fix it ;-)

Anyway, I have some other things in mind that I might try out now. Thanks for your effort so far, I really appreciate it!

**Comment by RobJinman** [comment]
Yeah sorry, it's because I only just came across Jonathan Blow's twitch video a few hours ago, and he was experiencing this problem so I felt an urgency to fix it.

**Comment by gonutz** [comment]
I saw that stream as well, it brought me to your game in the first place. I find this game great so I wanted to work on this problem as I imagined it could not be that hard to figure out. After all, your changes are not that large and you fixed it quickly once you worked on it.

The thing that makes me feel bad about your last comment is that you say

> he was experiencing this problem so I felt an urgency to fix it

which sounds to me like what he says is more important than the people filing issues on Github. I know this is not the case and I guess you do not actually see it that way - but this is how it comes off. My head says this is not a big deal but I notice that I am less excited to work on the code because of it.

Putting it in perspective, Jon Blow is somebody I follow regularly and I admire what he does. Still, he is not an open source contributor, all we see him do in his streams is complain about software every now and then - which is fine, I do that all the time. Devs mess up often and produce unusable software left and right so when I encounter a bad program I typically stop using it and tell people to avoid it. That is fine.

On the other hand I have also contributed to open source projects in the past and I am happy about everybody that forks and improves my repos as well. The open source community thrives on cooperation. I have never seen Jon Blow file an issue or notify a dev of their bugs on stream. Not to say that he never does that but he seems to generally complain about things and then forget them. He did not post the mouse issue here. Had you not actively gone and watched his video, you would not have known about his experiences.

My point is that Jon Blow created a video where he talks snarky about "these itch.io games" and makes you look bad and gives his rant about developers not caring about quality. Then I saw that video and the mouse problem, felt intrigued by your game, downloaded and played it, looked things up to find this repo, created a Github issue, forked your code, went through a large setup phase, creating another issue in the process and got ready to actually make real changes to the code. Then right at this time you go see his video and solve the problem in an hour.

The question on my mind is, why did you not just solve the issue right away when I filed it? Why is it so much more urgent when someone on twitch talks about your game in a condescending way than when an actual contributor who is ready to put in some work creates an issue?

As I said, in my head I know this is not a big deal and that you do not really think any of the above - I just wrote down the feeling that your last comment conveyed to me.

**Comment by RobJinman** [comment]
> which sounds to me like what he says is more important than the people filing issues on Github.

At the time you created this issue, I thought it was a minor problem that only occurs rarely (unless you really force it to happen). That was the case for me during testing. I do all my development on two rather low-res monitors so the game window is a larger portion of the screen. Fixing this was therefore low priority. I was excited that you were thinking of fixing it as I've never had someone contribute to one of my projects before. I didn't want to do any more work on this project, as I wanted to move onto other things.

You can imagine my excitement though when the creator of my current favourite game, The Witness, shared a video of himself playing my game, and then subsequent disappointment when the game failed to perform adequately on his setup (4K display, sensitive mouse). I just has to fix it ASAP.

I'm super grateful for your help though. If you'd like to look into another issue, there's a problem on some Windows machines where the sound effects are delayed. You could try and reproduce that. It happens on my work laptop, but none of my home computers.

Or perhaps you could try making some new levels for the game, or extending an existing one. The game's map files are svg images, which I edit with Inkscape. However, it's a finicky process and I haven't written any documentation on how it works exactly, and it's very hard to debug a bad game map.

Anyway, sorry if I've wasted your time. I just had to get that bug fixed immediately after seeing how bad it was.

**Comment by gonutz** [comment]
I understand your reasons much better now, thanks for this detailed explanation of your thought process, I really appreciate this very much. You totally brought back my motivation here.

Also nice to hear your suggestions. I was thinking about something else first, though. This hooks into the other thing that Jon Blow said on that stream, about everything being just one pixel.

I would like to add the buttons 1, 2, 3 and maybe more to set the zoom level of the FPS game window. I wanted to have the window larger as well. What I did was just lower my resolution when I played the game but that is obviously not a good solution :-)

There are several possible ways to implement a UI for this, I first thought about doing it automatically depending on your screen size or adding another window menu entry for this but that does not seem to be a good fit for the game. Instead I think it would be nice to include the number keys in the instructions menu when you first see it. That time when you realize that the instructions are actually a wall inside the FPS world - a very cool moment by the way!

Having the keys 1, 2, 3 there besides the WASDE and Space would be a solution that fits the rest of the game well in my opinion. It is really a minor change, it clutters the instruction sheet a tiny bit but the benfits outweigh the cost for this.

Pressing 1 would give you the regular zoom level, the size it has in the current version of the game. 2 doubles the size etc.

What do you think about this feature? If you are into it I would open another issue here and try to implement it.

**Comment by RobJinman** [comment]
Perhaps something like this?

![Controls](https://i.imgur.com/8rbZQul.png)

Not sure though.

**Comment by RobJinman** [comment]
Perhaps just make it bigger for everyone. The resolution of the actual render target can't be any higher though because the 3D engine is so inefficient, but we can scale it up a bit.

**Comment by gonutz** [comment]
I think Page Up/Down is a good idea, this way you can adjust it to what you want. The problem with making it larger in the first place is in the settings dialog right before you first play it. It would kind of ruin the surprise if the settings window would be four times the size of the main window...

I just tried to simply change the window size of the FPS window but the window stays the same while the content is resized. I tried `setGeometry`, `setFixedSize`, `resize`, `adjustSize` and various combinations of these both on the widget itself and on its parents. I just don't know how this works in Qt...

Apart from that I experience another strange bug. After I start the program from VS using F5 or Ctrl+F5, so with or without the debugger running, I close the window, make some changes and try to run it again. But something locks the .exe file and it cannot be rebuilt. Waiting for a minute sometimes fixes the problem, sometimes I have to restart VS and sometimes it works starting the program two or three times in a row. Have you experienced anything like this?

**Comment by RobJinman** [comment]
Made a new issue to discuss our options: https://github.com/RobJinman/pro_office_calc/issues/8

Not experienced that bug myself. I do most development on Linux and just build on other platforms once I'm ready to release.

**Comment by Commenter25** [comment]
This is still a significant issue, at least on KDE Wayland. Since window size seems to be a major aspect of this discussion, perhaps it would help to integer scale the window. It'd still be sharp and low quality and pixel perfect, but the window would be much larger.
